// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3vQkRNFh1ivJhSISbxepa5aGqmztopo',
    appId: '1:717135300117:web:60627c644107093176701c',
    messagingSenderId: '717135300117',
    projectId: 'edusharedb-ee642',
    authDomain: 'edusharedb-ee642.firebaseapp.com',
    storageBucket: 'edusharedb-ee642.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIm207tfweVMKaE8j7RqlJ6BY4uj7vGgQ',
    appId: '1:717135300117:android:718db440c03ba0c876701c',
    messagingSenderId: '717135300117',
    projectId: 'edusharedb-ee642',
    storageBucket: 'edusharedb-ee642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR96IxYW__h10btZCaNYt8r5YE8c0dzTc',
    appId: '1:717135300117:ios:79fe35fc6516f67b76701c',
    messagingSenderId: '717135300117',
    projectId: 'edusharedb-ee642',
    storageBucket: 'edusharedb-ee642.firebasestorage.app',
    iosBundleId: 'com.example.edushare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR96IxYW__h10btZCaNYt8r5YE8c0dzTc',
    appId: '1:717135300117:ios:79fe35fc6516f67b76701c',
    messagingSenderId: '717135300117',
    projectId: 'edusharedb-ee642',
    storageBucket: 'edusharedb-ee642.firebasestorage.app',
    iosBundleId: 'com.example.edushare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA3vQkRNFh1ivJhSISbxepa5aGqmztopo',
    appId: '1:717135300117:web:ad56825ca3885a5d76701c',
    messagingSenderId: '717135300117',
    projectId: 'edusharedb-ee642',
    authDomain: 'edusharedb-ee642.firebaseapp.com',
    storageBucket: 'edusharedb-ee642.firebasestorage.app',
  );
}
